apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rollouts-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/app-root: "/"
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: rollouts-demo
            servicePort: 80