---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  labels:
    app: rollouts-demo
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: "shariqrizvi/simple-frontend:v3"
          ports:
          - containerPort: 3000
            protocol: TCP
#  strategy:
#     blueGreen:
#       activeService: rollouts-demo
#       previewService: rollouts-demo-preview
#     canary: 
#       steps:
#       - setWeight: 20
#       - pause: {}
