apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  labels:
    app: rollouts-demo
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: "shariqrizvi/simple-frontend:v5"
          ports:
          - containerPort: 3000
            protocol: TCP
  strategy:
     blueGreen:
       activeService: rollouts-demo
       previewService: rollouts-demo-preview
       previewReplicaCount: 5
       autoPromotionEnabled: true
       autoPromotionSeconds: 30
#     canary: 
#       steps:
#       - setWeight: 20
#       - pause: {}
